version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn run setup

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
