version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn add bcrypt-nodejs && yarn remove bcrypt
          name: fix bcrypt issue
      - run:
          command: yarn install
          name: install components
      - run:
          command: yarn build
          name: Build app
      - run:
          command: yarn start test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - build_and_test
