version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn add bcrypt
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
